# Generated by Django 5.2.10 on 2026-01-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="書名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                (
                    "isbn",
                    models.CharField(max_length=13, unique=True, verbose_name="ISBN"),
                ),
                (
                    "total_copies",
                    models.IntegerField(default=1, verbose_name="總館藏數"),
                ),
                (
                    "available_copies",
                    models.IntegerField(default=1, verbose_name="目前可借數"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorrowingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="借出時間"),
                ),
                ("due_date", models.DateTimeField(verbose_name="應還時間")),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="歸還時間"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.book",
                        verbose_name="書籍",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="借閱人",
                    ),
                ),
            ],
        ),
    ]
